// Unit Icons: traducciones del tab ICONOS (escena settings, antes de opciones.js). GENERADO por scripts/generar_idiomas.py desde data/traducciones.json.
// Traducciones automaticas sin revision nativa. Clave = texto en ingles (loc). Idioma activo: i18n.lng() (pl-PL -> pl, pt-BR -> pt, zh-HK -> zh-TW).
(function () {
    'use strict';
    var TRAD = {
 "es": {
  "ICONS": "ICONOS",
  "UNIT ICONS": "ICONOS DE UNIDADES",
  "Icon style": "Estilo de iconos",
  "Original (game icons)": "Original (iconos del juego)",
  "Outline": "Hueca",
  "Bevel": "Bisel",
  "Strategic icon size": "Tamaño de iconos estratégicos",
  "Strategic icon opacity": "Opacidad de iconos estratégicos",
  "Unit portrait opacity (selection / build bar)": "Opacidad del retrato de la unidad (selección / barra de construcción)",
  "STYLE BY DOMAIN": "ESTILO POR DOMINIO",
  "SIZE AND OPACITY BY CATEGORY": "TAMAÑO Y OPACIDAD POR CATEGORÍA",
  "RADAR BLIPS": "BLIPS DE RADAR",
  "PRESETS AND RESET": "PREAJUSTES Y RESTABLECER",
  "Same as general": "Igual que el general",
  "Style: land units": "Estilo: unidades terrestres",
  "Style: naval units": "Estilo: unidades navales",
  "Style: air units": "Estilo: unidades aéreas",
  "Style: orbital units": "Estilo: unidades orbitales",
  "Style: structures": "Estilo: estructuras",
  "Size: units": "Tamaño: unidades",
  "Size: structures": "Tamaño: estructuras",
  "Size: orbital units": "Tamaño: unidades orbitales",
  "Opacity: units": "Opacidad: unidades",
  "Opacity: structures": "Opacidad: estructuras",
  "Opacity: orbital units": "Opacidad: unidades orbitales",
  "Blip opacity": "Opacidad de blips",
  "Blip color": "Color de blips",
  "Preset": "Preajuste",
  "Team color": "Color de equipo",
  "Red": "Rojo",
  "Yellow": "Amarillo",
  "Green": "Verde",
  "Cyan": "Cian",
  "Blue": "Azul",
  "Magenta": "Magenta",
  "White": "Blanco",
  "Custom": "Personalizado",
  "Default": "Predeterminado",
  "Discreet": "Discreto",
  "High contrast": "Alto contraste",
  "Reset to defaults": "Restablecer valores",
  "SELECTION AND HOVER RINGS": "ANILLOS DE SELECCIÓN Y HOVER",
  "Selection ring style": "Estilo del anillo de selección",
  "Rainbow (dom314)": "Arcoíris (dom314)",
  "Hover ring color": "Color del anillo de hover",
  "Ring changes reload the game view.": "Los cambios de anillo recargan la vista de la partida.",
  "Translations are automatic and may contain errors.": "Las traducciones son automáticas y pueden contener errores.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "¿Quieres que añadamos un icono al mod? Avísanos en el Discord de Planetary Annihilation, canal #making-mods.",
  "Icon quality (Outline / Bevel)": "Calidad de iconos (Contorno / Bisel)",
  "Standard (52 px)": "Estándar (52 px)",
  "High (104 px)": "Alta (104 px)",
  "Very high (208 px)": "Muy alta (208 px)"
 },
 "fr": {
  "ICONS": "ICÔNES",
  "UNIT ICONS": "ICÔNES D'UNITÉS",
  "Icon style": "Style des icônes",
  "Original (game icons)": "Original (icônes du jeu)",
  "Outline": "Contour",
  "Bevel": "Biseauté",
  "Strategic icon size": "Taille des icônes stratégiques",
  "Strategic icon opacity": "Opacité des icônes stratégiques",
  "Unit portrait opacity (selection / build bar)": "Opacité du portrait de l'unité (sélection / barre de construction)",
  "STYLE BY DOMAIN": "STYLE PAR DOMAINE",
  "SIZE AND OPACITY BY CATEGORY": "TAILLE ET OPACITÉ PAR CATÉGORIE",
  "RADAR BLIPS": "ÉCHOS RADAR",
  "PRESETS AND RESET": "PRÉRÉGLAGES ET RÉINITIALISATION",
  "Same as general": "Comme le réglage général",
  "Style: land units": "Style: unités terrestres",
  "Style: naval units": "Style: unités navales",
  "Style: air units": "Style: unités aériennes",
  "Style: orbital units": "Style: unités orbitales",
  "Style: structures": "Style: structures",
  "Size: units": "Taille: unités",
  "Size: structures": "Taille: structures",
  "Size: orbital units": "Taille: unités orbitales",
  "Opacity: units": "Opacité: unités",
  "Opacity: structures": "Opacité: structures",
  "Opacity: orbital units": "Opacité: unités orbitales",
  "Blip opacity": "Opacité des échos",
  "Blip color": "Couleur des échos",
  "Preset": "Préréglage",
  "Team color": "Couleur d'équipe",
  "Red": "Rouge",
  "Yellow": "Jaune",
  "Green": "Vert",
  "Cyan": "Cyan",
  "Blue": "Bleu",
  "Magenta": "Magenta",
  "White": "Blanc",
  "Custom": "Personnalisé",
  "Default": "Par défaut",
  "Discreet": "Discret",
  "High contrast": "Contraste élevé",
  "Reset to defaults": "Rétablir les valeurs par défaut",
  "SELECTION AND HOVER RINGS": "ANNEAUX DE SÉLECTION ET DE SURVOL",
  "Selection ring style": "Style de l’anneau de sélection",
  "Rainbow (dom314)": "Arc-en-ciel (dom314)",
  "Hover ring color": "Couleur de l’anneau de survol",
  "Ring changes reload the game view.": "Les changements d’anneaux rechargent la vue de la partie.",
  "Translations are automatic and may contain errors.": "Les traductions sont automatiques et peuvent contenir des erreurs.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Vous voulez qu'on ajoute une icône au mod ? Dites-le-nous sur le Discord de Planetary Annihilation, canal #making-mods.",
  "Icon quality (Outline / Bevel)": "Qualité des icônes (Contour / Biseau)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Haute (104 px)",
  "Very high (208 px)": "Très haute (208 px)"
 },
 "de": {
  "ICONS": "SYMBOLE",
  "UNIT ICONS": "EINHEITENSYMBOLE",
  "Icon style": "Symbolstil",
  "Original (game icons)": "Original (Spielsymbole)",
  "Outline": "Umriss",
  "Bevel": "Abgeschrägt",
  "Strategic icon size": "Größe der strategischen Symbole",
  "Strategic icon opacity": "Deckkraft der strategischen Symbole",
  "Unit portrait opacity (selection / build bar)": "Deckkraft des Einheitenporträts (Auswahl / Baubalken)",
  "STYLE BY DOMAIN": "STIL NACH BEREICH",
  "SIZE AND OPACITY BY CATEGORY": "GRÖSSE UND DECKKRAFT NACH KATEGORIE",
  "RADAR BLIPS": "RADARSIGNALE",
  "PRESETS AND RESET": "VOREINSTELLUNGEN UND ZURÜCKSETZEN",
  "Same as general": "Wie allgemein",
  "Style: land units": "Stil: Landeinheiten",
  "Style: naval units": "Stil: Seeeinheiten",
  "Style: air units": "Stil: Lufteinheiten",
  "Style: orbital units": "Stil: Orbitaleinheiten",
  "Style: structures": "Stil: Gebäude",
  "Size: units": "Größe: Einheiten",
  "Size: structures": "Größe: Gebäude",
  "Size: orbital units": "Größe: Orbitaleinheiten",
  "Opacity: units": "Deckkraft: Einheiten",
  "Opacity: structures": "Deckkraft: Gebäude",
  "Opacity: orbital units": "Deckkraft: Orbitaleinheiten",
  "Blip opacity": "Deckkraft der Radarsignale",
  "Blip color": "Farbe der Radarsignale",
  "Preset": "Voreinstellung",
  "Team color": "Teamfarbe",
  "Red": "Rot",
  "Yellow": "Gelb",
  "Green": "Grün",
  "Cyan": "Cyan",
  "Blue": "Blau",
  "Magenta": "Magenta",
  "White": "Weiß",
  "Custom": "Benutzerdefiniert",
  "Default": "Standard",
  "Discreet": "Dezent",
  "High contrast": "Hoher Kontrast",
  "Reset to defaults": "Auf Standard zurücksetzen",
  "SELECTION AND HOVER RINGS": "AUSWAHL- UND HOVER-RINGE",
  "Selection ring style": "Stil des Auswahlrings",
  "Rainbow (dom314)": "Regenbogen (dom314)",
  "Hover ring color": "Farbe des Hover-Rings",
  "Ring changes reload the game view.": "Änderungen an Ringen laden die Spielansicht neu.",
  "Translations are automatic and may contain errors.": "Die Übersetzungen sind automatisch und können Fehler enthalten.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Möchtest du ein Symbol im Mod ergänzt haben? Sag uns Bescheid im Planetary-Annihilation-Discord, Kanal #making-mods.",
  "Icon quality (Outline / Bevel)": "Symbolqualität (Umriss / Abschrägung)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Hoch (104 px)",
  "Very high (208 px)": "Sehr hoch (208 px)"
 },
 "it": {
  "ICONS": "ICONE",
  "UNIT ICONS": "ICONE DELLE UNITÀ",
  "Icon style": "Stile delle icone",
  "Original (game icons)": "Originale (icone del gioco)",
  "Outline": "Contorno",
  "Bevel": "Smussato",
  "Strategic icon size": "Dimensione delle icone strategiche",
  "Strategic icon opacity": "Opacità delle icone strategiche",
  "Unit portrait opacity (selection / build bar)": "Opacità del ritratto dell'unità (selezione / barra di costruzione)",
  "STYLE BY DOMAIN": "STILE PER DOMINIO",
  "SIZE AND OPACITY BY CATEGORY": "DIMENSIONE E OPACITÀ PER CATEGORIA",
  "RADAR BLIPS": "SEGNALI RADAR",
  "PRESETS AND RESET": "PRESET E RIPRISTINO",
  "Same as general": "Come impostazione generale",
  "Style: land units": "Stile: unità terrestri",
  "Style: naval units": "Stile: unità navali",
  "Style: air units": "Stile: unità aeree",
  "Style: orbital units": "Stile: unità orbitali",
  "Style: structures": "Stile: strutture",
  "Size: units": "Dimensione: unità",
  "Size: structures": "Dimensione: strutture",
  "Size: orbital units": "Dimensione: unità orbitali",
  "Opacity: units": "Opacità: unità",
  "Opacity: structures": "Opacità: strutture",
  "Opacity: orbital units": "Opacità: unità orbitali",
  "Blip opacity": "Opacità dei segnali",
  "Blip color": "Colore dei segnali",
  "Preset": "Preset",
  "Team color": "Colore della squadra",
  "Red": "Rosso",
  "Yellow": "Giallo",
  "Green": "Verde",
  "Cyan": "Ciano",
  "Blue": "Blu",
  "Magenta": "Magenta",
  "White": "Bianco",
  "Custom": "Personalizzato",
  "Default": "Predefinito",
  "Discreet": "Discreto",
  "High contrast": "Alto contrasto",
  "Reset to defaults": "Ripristina predefiniti",
  "SELECTION AND HOVER RINGS": "ANELLI DI SELEZIONE E PASSAGGIO DEL MOUSE",
  "Selection ring style": "Stile dell’anello di selezione",
  "Rainbow (dom314)": "Arcobaleno (dom314)",
  "Hover ring color": "Colore dell’anello al passaggio del mouse",
  "Ring changes reload the game view.": "Le modifiche agli anelli ricaricano la vista della partita.",
  "Translations are automatic and may contain errors.": "Le traduzioni sono automatiche e possono contenere errori.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Vuoi che aggiungiamo un'icona al mod? Faccelo sapere sul Discord di Planetary Annihilation, canale #making-mods.",
  "Icon quality (Outline / Bevel)": "Qualità delle icone (Contorno / Smussato)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Alta (104 px)",
  "Very high (208 px)": "Molto alta (208 px)"
 },
 "pt": {
  "ICONS": "ÍCONES",
  "UNIT ICONS": "ÍCONES DE UNIDADES",
  "Icon style": "Estilo dos ícones",
  "Original (game icons)": "Original (ícones do jogo)",
  "Outline": "Contorno",
  "Bevel": "Chanfrado",
  "Strategic icon size": "Tamanho dos ícones estratégicos",
  "Strategic icon opacity": "Opacidade dos ícones estratégicos",
  "Unit portrait opacity (selection / build bar)": "Opacidade do retrato da unidade (seleção / barra de construção)",
  "STYLE BY DOMAIN": "ESTILO POR DOMÍNIO",
  "SIZE AND OPACITY BY CATEGORY": "TAMANHO E OPACIDADE POR CATEGORIA",
  "RADAR BLIPS": "BLIPS DE RADAR",
  "PRESETS AND RESET": "PREDEFINIÇÕES E REDEFINIR",
  "Same as general": "Igual ao geral",
  "Style: land units": "Estilo: unidades terrestres",
  "Style: naval units": "Estilo: unidades navais",
  "Style: air units": "Estilo: unidades aéreas",
  "Style: orbital units": "Estilo: unidades orbitais",
  "Style: structures": "Estilo: estruturas",
  "Size: units": "Tamanho: unidades",
  "Size: structures": "Tamanho: estruturas",
  "Size: orbital units": "Tamanho: unidades orbitais",
  "Opacity: units": "Opacidade: unidades",
  "Opacity: structures": "Opacidade: estruturas",
  "Opacity: orbital units": "Opacidade: unidades orbitais",
  "Blip opacity": "Opacidade dos blips",
  "Blip color": "Cor dos blips",
  "Preset": "Predefinição",
  "Team color": "Cor da equipe",
  "Red": "Vermelho",
  "Yellow": "Amarelo",
  "Green": "Verde",
  "Cyan": "Ciano",
  "Blue": "Azul",
  "Magenta": "Magenta",
  "White": "Branco",
  "Custom": "Personalizado",
  "Default": "Padrão",
  "Discreet": "Discreto",
  "High contrast": "Alto contraste",
  "Reset to defaults": "Redefinir para o padrão",
  "SELECTION AND HOVER RINGS": "ANÉIS DE SELEÇÃO E SOB O CURSOR",
  "Selection ring style": "Estilo do anel de seleção",
  "Rainbow (dom314)": "Arco-íris (dom314)",
  "Hover ring color": "Cor do anel sob o cursor",
  "Ring changes reload the game view.": "As alterações dos anéis recarregam a vista da partida.",
  "Translations are automatic and may contain errors.": "As traduções são automáticas e podem conter erros.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Quer que adicionemos um ícone ao mod? Avise-nos no Discord de Planetary Annihilation, canal #making-mods.",
  "Icon quality (Outline / Bevel)": "Qualidade dos ícones (Contorno / Chanfro)",
  "Standard (52 px)": "Padrão (52 px)",
  "High (104 px)": "Alta (104 px)",
  "Very high (208 px)": "Muito alta (208 px)"
 },
 "ru": {
  "ICONS": "ЗНАЧКИ",
  "UNIT ICONS": "ЗНАЧКИ ЮНИТОВ",
  "Icon style": "Стиль значков",
  "Original (game icons)": "Оригинал (значки игры)",
  "Outline": "Контур",
  "Bevel": "Фаска",
  "Strategic icon size": "Размер стратегических значков",
  "Strategic icon opacity": "Непрозрачность стратегических значков",
  "Unit portrait opacity (selection / build bar)": "Непрозрачность портрета юнита (выделение / панель строительства)",
  "STYLE BY DOMAIN": "СТИЛЬ ПО ТИПАМ",
  "SIZE AND OPACITY BY CATEGORY": "РАЗМЕР И НЕПРОЗРАЧНОСТЬ ПО КАТЕГОРИЯМ",
  "RADAR BLIPS": "ОТМЕТКИ РАДАРА",
  "PRESETS AND RESET": "ПРЕСЕТЫ И СБРОС",
  "Same as general": "Как в общих настройках",
  "Style: land units": "Стиль: наземные юниты",
  "Style: naval units": "Стиль: морские юниты",
  "Style: air units": "Стиль: воздушные юниты",
  "Style: orbital units": "Стиль: орбитальные юниты",
  "Style: structures": "Стиль: строения",
  "Size: units": "Размер: юниты",
  "Size: structures": "Размер: строения",
  "Size: orbital units": "Размер: орбитальные юниты",
  "Opacity: units": "Непрозрачность: юниты",
  "Opacity: structures": "Непрозрачность: строения",
  "Opacity: orbital units": "Непрозрачность: орбитальные юниты",
  "Blip opacity": "Непрозрачность отметок",
  "Blip color": "Цвет отметок",
  "Preset": "Пресет",
  "Team color": "Цвет команды",
  "Red": "Красный",
  "Yellow": "Жёлтый",
  "Green": "Зелёный",
  "Cyan": "Голубой",
  "Blue": "Синий",
  "Magenta": "Пурпурный",
  "White": "Белый",
  "Custom": "Свой",
  "Default": "По умолчанию",
  "Discreet": "Неприметный",
  "High contrast": "Высокий контраст",
  "Reset to defaults": "Сбросить настройки",
  "SELECTION AND HOVER RINGS": "КОЛЬЦА ВЫДЕЛЕНИЯ И НАВЕДЕНИЯ",
  "Selection ring style": "Стиль кольца выделения",
  "Rainbow (dom314)": "Радуга (dom314)",
  "Hover ring color": "Цвет кольца наведения",
  "Ring changes reload the game view.": "Изменения колец перезагружают вид игры.",
  "Translations are automatic and may contain errors.": "Переводы выполнены автоматически и могут содержать ошибки.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Хотите, чтобы в мод добавили значок? Напишите нам в Discord Planetary Annihilation, канал #making-mods.",
  "Icon quality (Outline / Bevel)": "Качество значков (Контур / Скос)",
  "Standard (52 px)": "Стандартное (52 px)",
  "High (104 px)": "Высокое (104 px)",
  "Very high (208 px)": "Очень высокое (208 px)"
 },
 "uk": {
  "ICONS": "ЗНАЧКИ",
  "UNIT ICONS": "ЗНАЧКИ ЮНІТІВ",
  "Icon style": "Стиль значків",
  "Original (game icons)": "Оригінал (значки гри)",
  "Outline": "Контур",
  "Bevel": "Фаска",
  "Strategic icon size": "Розмір стратегічних значків",
  "Strategic icon opacity": "Непрозорість стратегічних значків",
  "Unit portrait opacity (selection / build bar)": "Непрозорість портрета юніта (виділення / панель будівництва)",
  "STYLE BY DOMAIN": "СТИЛЬ ЗА ТИПАМИ",
  "SIZE AND OPACITY BY CATEGORY": "РОЗМІР І НЕПРОЗОРІСТЬ ЗА КАТЕГОРІЯМИ",
  "RADAR BLIPS": "ВІДМІТКИ РАДАРА",
  "PRESETS AND RESET": "ПРЕСЕТИ ТА СКИДАННЯ",
  "Same as general": "Як у загальних налаштуваннях",
  "Style: land units": "Стиль: наземні юніти",
  "Style: naval units": "Стиль: морські юніти",
  "Style: air units": "Стиль: повітряні юніти",
  "Style: orbital units": "Стиль: орбітальні юніти",
  "Style: structures": "Стиль: споруди",
  "Size: units": "Розмір: юніти",
  "Size: structures": "Розмір: споруди",
  "Size: orbital units": "Розмір: орбітальні юніти",
  "Opacity: units": "Непрозорість: юніти",
  "Opacity: structures": "Непрозорість: споруди",
  "Opacity: orbital units": "Непрозорість: орбітальні юніти",
  "Blip opacity": "Непрозорість відміток",
  "Blip color": "Колір відміток",
  "Preset": "Пресет",
  "Team color": "Колір команди",
  "Red": "Червоний",
  "Yellow": "Жовтий",
  "Green": "Зелений",
  "Cyan": "Блакитний",
  "Blue": "Синій",
  "Magenta": "Пурпуровий",
  "White": "Білий",
  "Custom": "Власний",
  "Default": "За замовчуванням",
  "Discreet": "Непомітний",
  "High contrast": "Високий контраст",
  "Reset to defaults": "Скинути налаштування",
  "SELECTION AND HOVER RINGS": "КІЛЬЦЯ ВИБОРУ ТА НАВЕДЕННЯ",
  "Selection ring style": "Стиль кільця вибору",
  "Rainbow (dom314)": "Веселка (dom314)",
  "Hover ring color": "Колір кільця наведення",
  "Ring changes reload the game view.": "Зміни кілець перезавантажують вигляд гри.",
  "Translations are automatic and may contain errors.": "Переклади виконано автоматично, і вони можуть містити помилки.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Хочете, щоб до моду додали значок? Напишіть нам у Discord Planetary Annihilation, канал #making-mods.",
  "Icon quality (Outline / Bevel)": "Якість значків (Контур / Скіс)",
  "Standard (52 px)": "Стандартна (52 px)",
  "High (104 px)": "Висока (104 px)",
  "Very high (208 px)": "Дуже висока (208 px)"
 },
 "pl": {
  "ICONS": "IKONY",
  "UNIT ICONS": "IKONY JEDNOSTEK",
  "Icon style": "Styl ikon",
  "Original (game icons)": "Oryginał (ikony gry)",
  "Outline": "Kontur",
  "Bevel": "Skos",
  "Strategic icon size": "Rozmiar ikon strategicznych",
  "Strategic icon opacity": "Przezroczystość ikon strategicznych",
  "Unit portrait opacity (selection / build bar)": "Przezroczystość portretu jednostki (zaznaczenie / pasek budowy)",
  "STYLE BY DOMAIN": "STYL WEDŁUG DOMENY",
  "SIZE AND OPACITY BY CATEGORY": "ROZMIAR I PRZEZROCZYSTOŚĆ WG KATEGORII",
  "RADAR BLIPS": "ECHA RADARU",
  "PRESETS AND RESET": "PRESETY I RESET",
  "Same as general": "Jak ogólnie",
  "Style: land units": "Styl: jednostki lądowe",
  "Style: naval units": "Styl: jednostki morskie",
  "Style: air units": "Styl: jednostki powietrzne",
  "Style: orbital units": "Styl: jednostki orbitalne",
  "Style: structures": "Styl: budowle",
  "Size: units": "Rozmiar: jednostki",
  "Size: structures": "Rozmiar: budowle",
  "Size: orbital units": "Rozmiar: jednostki orbitalne",
  "Opacity: units": "Przezroczystość: jednostki",
  "Opacity: structures": "Przezroczystość: budowle",
  "Opacity: orbital units": "Przezroczystość: jednostki orbitalne",
  "Blip opacity": "Przezroczystość ech",
  "Blip color": "Kolor ech",
  "Preset": "Preset",
  "Team color": "Kolor drużyny",
  "Red": "Czerwony",
  "Yellow": "Żółty",
  "Green": "Zielony",
  "Cyan": "Cyjan",
  "Blue": "Niebieski",
  "Magenta": "Magenta",
  "White": "Biały",
  "Custom": "Własny",
  "Default": "Domyślny",
  "Discreet": "Dyskretny",
  "High contrast": "Wysoki kontrast",
  "Reset to defaults": "Przywróć domyślne",
  "SELECTION AND HOVER RINGS": "PIERŚCIENIE WYBORU I WSKAZANIA",
  "Selection ring style": "Styl pierścienia wyboru",
  "Rainbow (dom314)": "Tęcza (dom314)",
  "Hover ring color": "Kolor pierścienia wskazania",
  "Ring changes reload the game view.": "Zmiany pierścieni ponownie wczytują widok gry.",
  "Translations are automatic and may contain errors.": "Tłumaczenia są automatyczne i mogą zawierać błędy.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Chcesz, żebyśmy dodali ikonę do moda? Daj nam znać na Discordzie Planetary Annihilation, kanał #making-mods.",
  "Icon quality (Outline / Bevel)": "Jakość ikon (Kontur / Skos)",
  "Standard (52 px)": "Standardowa (52 px)",
  "High (104 px)": "Wysoka (104 px)",
  "Very high (208 px)": "Bardzo wysoka (208 px)"
 },
 "cs": {
  "ICONS": "IKONY",
  "UNIT ICONS": "IKONY JEDNOTEK",
  "Icon style": "Styl ikon",
  "Original (game icons)": "Originál (ikony hry)",
  "Outline": "Obrys",
  "Bevel": "Zkosený",
  "Strategic icon size": "Velikost strategických ikon",
  "Strategic icon opacity": "Průhlednost strategických ikon",
  "Unit portrait opacity (selection / build bar)": "Průhlednost portrétu jednotky (výběr / panel výstavby)",
  "STYLE BY DOMAIN": "STYL PODLE DOMÉNY",
  "SIZE AND OPACITY BY CATEGORY": "VELIKOST A PRŮHLEDNOST PODLE KATEGORIE",
  "RADAR BLIPS": "RADAROVÉ ZNAČKY",
  "PRESETS AND RESET": "PŘEDVOLBY A OBNOVENÍ",
  "Same as general": "Stejně jako obecně",
  "Style: land units": "Styl: pozemní jednotky",
  "Style: naval units": "Styl: námořní jednotky",
  "Style: air units": "Styl: letecké jednotky",
  "Style: orbital units": "Styl: orbitální jednotky",
  "Style: structures": "Styl: budovy",
  "Size: units": "Velikost: jednotky",
  "Size: structures": "Velikost: budovy",
  "Size: orbital units": "Velikost: orbitální jednotky",
  "Opacity: units": "Průhlednost: jednotky",
  "Opacity: structures": "Průhlednost: budovy",
  "Opacity: orbital units": "Průhlednost: orbitální jednotky",
  "Blip opacity": "Průhlednost značek",
  "Blip color": "Barva značek",
  "Preset": "Předvolba",
  "Team color": "Barva týmu",
  "Red": "Červená",
  "Yellow": "Žlutá",
  "Green": "Zelená",
  "Cyan": "Azurová",
  "Blue": "Modrá",
  "Magenta": "Purpurová",
  "White": "Bílá",
  "Custom": "Vlastní",
  "Default": "Výchozí",
  "Discreet": "Nenápadná",
  "High contrast": "Vysoký kontrast",
  "Reset to defaults": "Obnovit výchozí",
  "SELECTION AND HOVER RINGS": "KRUHY VÝBĚRU A NAJETÍ KURZORU",
  "Selection ring style": "Styl kruhu výběru",
  "Rainbow (dom314)": "Duha (dom314)",
  "Hover ring color": "Barva kruhu pod kurzorem",
  "Ring changes reload the game view.": "Změny kruhů znovu načtou pohled hry.",
  "Translations are automatic and may contain errors.": "Překlady jsou automatické a mohou obsahovat chyby.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Chcete do modu přidat ikonu? Dejte nám vědět na Discordu Planetary Annihilation, kanál #making-mods.",
  "Icon quality (Outline / Bevel)": "Kvalita ikon (Obrys / Zkosení)",
  "Standard (52 px)": "Standardní (52 px)",
  "High (104 px)": "Vysoká (104 px)",
  "Very high (208 px)": "Velmi vysoká (208 px)"
 },
 "da": {
  "ICONS": "IKONER",
  "UNIT ICONS": "ENHEDSIKONER",
  "Icon style": "Ikonstil",
  "Original (game icons)": "Original (spillets ikoner)",
  "Outline": "Omrids",
  "Bevel": "Affasning",
  "Strategic icon size": "Størrelse på strategiske ikoner",
  "Strategic icon opacity": "Gennemsigtighed for strategiske ikoner",
  "Unit portrait opacity (selection / build bar)": "Gennemsigtighed for enhedens portræt (valg / byggelinje)",
  "STYLE BY DOMAIN": "STIL EFTER DOMÆNE",
  "SIZE AND OPACITY BY CATEGORY": "STØRRELSE OG GENNEMSIGTIGHED EFTER KATEGORI",
  "RADAR BLIPS": "RADARPRIKKER",
  "PRESETS AND RESET": "FORUDINDSTILLINGER OG NULSTIL",
  "Same as general": "Samme som generelt",
  "Style: land units": "Stil: landenheder",
  "Style: naval units": "Stil: søenheder",
  "Style: air units": "Stil: luftenheder",
  "Style: orbital units": "Stil: orbitalenheder",
  "Style: structures": "Stil: bygninger",
  "Size: units": "Størrelse: enheder",
  "Size: structures": "Størrelse: bygninger",
  "Size: orbital units": "Størrelse: orbitalenheder",
  "Opacity: units": "Gennemsigtighed: enheder",
  "Opacity: structures": "Gennemsigtighed: bygninger",
  "Opacity: orbital units": "Gennemsigtighed: orbitalenheder",
  "Blip opacity": "Gennemsigtighed for prikker",
  "Blip color": "Farve på prikker",
  "Preset": "Forudindstilling",
  "Team color": "Holdfarve",
  "Red": "Rød",
  "Yellow": "Gul",
  "Green": "Grøn",
  "Cyan": "Cyan",
  "Blue": "Blå",
  "Magenta": "Magenta",
  "White": "Hvid",
  "Custom": "Brugerdefineret",
  "Default": "Standard",
  "Discreet": "Diskret",
  "High contrast": "Høj kontrast",
  "Reset to defaults": "Nulstil til standard",
  "SELECTION AND HOVER RINGS": "MARKERINGS- OG PEGERINGE",
  "Selection ring style": "Markeringsringens stil",
  "Rainbow (dom314)": "Regnbue (dom314)",
  "Hover ring color": "Farve på ring under markøren",
  "Ring changes reload the game view.": "Ændringer af ringe genindlæser spilvisningen.",
  "Translations are automatic and may contain errors.": "Oversættelserne er automatiske og kan indeholde fejl.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Vil du have en ikon tilføjet til modden? Sig til på Planetary Annihilations Discord, kanalen #making-mods.",
  "Icon quality (Outline / Bevel)": "Ikonkvalitet (Omrids / Affasning)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Høj (104 px)",
  "Very high (208 px)": "Meget høj (208 px)"
 },
 "fi": {
  "ICONS": "KUVAKKEET",
  "UNIT ICONS": "YKSIKKÖKUVAKKEET",
  "Icon style": "Kuvakkeiden tyyli",
  "Original (game icons)": "Alkuperäinen (pelin kuvakkeet)",
  "Outline": "Ääriviiva",
  "Bevel": "Viistetty",
  "Strategic icon size": "Strategisten kuvakkeiden koko",
  "Strategic icon opacity": "Strategisten kuvakkeiden läpinäkyvyys",
  "Unit portrait opacity (selection / build bar)": "Yksikön muotokuvan läpinäkyvyys (valinta / rakennuspalkki)",
  "STYLE BY DOMAIN": "TYYLI ALUEITTAIN",
  "SIZE AND OPACITY BY CATEGORY": "KOKO JA LÄPINÄKYVYYS LUOKITTAIN",
  "RADAR BLIPS": "TUTKAPISTEET",
  "PRESETS AND RESET": "ESIASETUKSET JA PALAUTUS",
  "Same as general": "Sama kuin yleinen",
  "Style: land units": "Tyyli: maayksiköt",
  "Style: naval units": "Tyyli: meriyksiköt",
  "Style: air units": "Tyyli: ilmayksiköt",
  "Style: orbital units": "Tyyli: kiertoratayksiköt",
  "Style: structures": "Tyyli: rakennukset",
  "Size: units": "Koko: yksiköt",
  "Size: structures": "Koko: rakennukset",
  "Size: orbital units": "Koko: kiertoratayksiköt",
  "Opacity: units": "Läpinäkyvyys: yksiköt",
  "Opacity: structures": "Läpinäkyvyys: rakennukset",
  "Opacity: orbital units": "Läpinäkyvyys: kiertoratayksiköt",
  "Blip opacity": "Pisteiden läpinäkyvyys",
  "Blip color": "Pisteiden väri",
  "Preset": "Esiasetus",
  "Team color": "Joukkueen väri",
  "Red": "Punainen",
  "Yellow": "Keltainen",
  "Green": "Vihreä",
  "Cyan": "Syaani",
  "Blue": "Sininen",
  "Magenta": "Magenta",
  "White": "Valkoinen",
  "Custom": "Oma",
  "Default": "Oletus",
  "Discreet": "Hillitty",
  "High contrast": "Korkea kontrasti",
  "Reset to defaults": "Palauta oletukset",
  "SELECTION AND HOVER RINGS": "VALINTA- JA OSOITINRENKAAT",
  "Selection ring style": "Valintarenkaan tyyli",
  "Rainbow (dom314)": "Sateenkaari (dom314)",
  "Hover ring color": "Osoitinrenkaan väri",
  "Ring changes reload the game view.": "Renkaiden muutokset lataavat pelinäkymän uudelleen.",
  "Translations are automatic and may contain errors.": "Käännökset on tehty automaattisesti, ja niissä voi olla virheitä.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Haluatko, että modiin lisätään kuvake? Kerro meille Planetary Annihilationin Discordissa, kanavalla #making-mods.",
  "Icon quality (Outline / Bevel)": "Kuvakkeiden laatu (Ääriviiva / Viiste)",
  "Standard (52 px)": "Vakio (52 px)",
  "High (104 px)": "Korkea (104 px)",
  "Very high (208 px)": "Erittäin korkea (208 px)"
 },
 "hu": {
  "ICONS": "IKONOK",
  "UNIT ICONS": "EGYSÉGIKONOK",
  "Icon style": "Ikonstílus",
  "Original (game icons)": "Eredeti (a játék ikonjai)",
  "Outline": "Körvonal",
  "Bevel": "Letört él",
  "Strategic icon size": "Stratégiai ikonok mérete",
  "Strategic icon opacity": "Stratégiai ikonok átlátszatlansága",
  "Unit portrait opacity (selection / build bar)": "Az egység portréjának átlátszatlansága (kijelölés / építősáv)",
  "STYLE BY DOMAIN": "STÍLUS TERÜLETENKÉNT",
  "SIZE AND OPACITY BY CATEGORY": "MÉRET ÉS ÁTLÁTSZATLANSÁG KATEGÓRIÁNKÉNT",
  "RADAR BLIPS": "RADARJELEK",
  "PRESETS AND RESET": "ELŐBEÁLLÍTÁSOK ÉS VISSZAÁLLÍTÁS",
  "Same as general": "Mint az általános",
  "Style: land units": "Stílus: szárazföldi egységek",
  "Style: naval units": "Stílus: tengeri egységek",
  "Style: air units": "Stílus: légi egységek",
  "Style: orbital units": "Stílus: orbitális egységek",
  "Style: structures": "Stílus: építmények",
  "Size: units": "Méret: egységek",
  "Size: structures": "Méret: építmények",
  "Size: orbital units": "Méret: orbitális egységek",
  "Opacity: units": "Átlátszatlanság: egységek",
  "Opacity: structures": "Átlátszatlanság: építmények",
  "Opacity: orbital units": "Átlátszatlanság: orbitális egységek",
  "Blip opacity": "Jelek átlátszatlansága",
  "Blip color": "Jelek színe",
  "Preset": "Előbeállítás",
  "Team color": "Csapatszín",
  "Red": "Piros",
  "Yellow": "Sárga",
  "Green": "Zöld",
  "Cyan": "Ciánkék",
  "Blue": "Kék",
  "Magenta": "Bíbor",
  "White": "Fehér",
  "Custom": "Egyéni",
  "Default": "Alapértelmezett",
  "Discreet": "Visszafogott",
  "High contrast": "Magas kontraszt",
  "Reset to defaults": "Alapértékek visszaállítása",
  "SELECTION AND HOVER RINGS": "KIJELÖLÉSI ÉS RÁMUTATÁSI GYŰRŰK",
  "Selection ring style": "Kijelölési gyűrű stílusa",
  "Rainbow (dom314)": "Szivárvány (dom314)",
  "Hover ring color": "Rámutatási gyűrű színe",
  "Ring changes reload the game view.": "A gyűrűk változásai újratöltik a játék nézetét.",
  "Translations are automatic and may contain errors.": "A fordítások automatikusak, és hibákat tartalmazhatnak.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Szeretnéd, hogy felvegyünk egy ikont a modba? Szólj nekünk a Planetary Annihilation Discordján, a #making-mods csatornán.",
  "Icon quality (Outline / Bevel)": "Ikonminőség (Körvonal / Letörés)",
  "Standard (52 px)": "Normál (52 px)",
  "High (104 px)": "Magas (104 px)",
  "Very high (208 px)": "Nagyon magas (208 px)"
 },
 "nl": {
  "ICONS": "PICTOGRAMMEN",
  "UNIT ICONS": "EENHEIDPICTOGRAMMEN",
  "Icon style": "Pictogramstijl",
  "Original (game icons)": "Origineel (spelpictogrammen)",
  "Outline": "Omtrek",
  "Bevel": "Afschuining",
  "Strategic icon size": "Grootte van strategische pictogrammen",
  "Strategic icon opacity": "Dekking van strategische pictogrammen",
  "Unit portrait opacity (selection / build bar)": "Dekking van het eenheidsportret (selectie / bouwbalk)",
  "STYLE BY DOMAIN": "STIJL PER DOMEIN",
  "SIZE AND OPACITY BY CATEGORY": "GROOTTE EN DEKKING PER CATEGORIE",
  "RADAR BLIPS": "RADARBLIPS",
  "PRESETS AND RESET": "VOORINSTELLINGEN EN RESETTEN",
  "Same as general": "Zelfde als algemeen",
  "Style: land units": "Stijl: landeenheden",
  "Style: naval units": "Stijl: zee-eenheden",
  "Style: air units": "Stijl: luchteenheden",
  "Style: orbital units": "Stijl: orbitale eenheden",
  "Style: structures": "Stijl: gebouwen",
  "Size: units": "Grootte: eenheden",
  "Size: structures": "Grootte: gebouwen",
  "Size: orbital units": "Grootte: orbitale eenheden",
  "Opacity: units": "Dekking: eenheden",
  "Opacity: structures": "Dekking: gebouwen",
  "Opacity: orbital units": "Dekking: orbitale eenheden",
  "Blip opacity": "Dekking van blips",
  "Blip color": "Kleur van blips",
  "Preset": "Voorinstelling",
  "Team color": "Teamkleur",
  "Red": "Rood",
  "Yellow": "Geel",
  "Green": "Groen",
  "Cyan": "Cyaan",
  "Blue": "Blauw",
  "Magenta": "Magenta",
  "White": "Wit",
  "Custom": "Aangepast",
  "Default": "Standaard",
  "Discreet": "Discreet",
  "High contrast": "Hoog contrast",
  "Reset to defaults": "Standaardwaarden herstellen",
  "SELECTION AND HOVER RINGS": "SELECTIE- EN AANWIJSRINGEN",
  "Selection ring style": "Stijl van de selectiering",
  "Rainbow (dom314)": "Regenboog (dom314)",
  "Hover ring color": "Kleur van de aanwijsring",
  "Ring changes reload the game view.": "Wijzigingen aan ringen laden de spelweergave opnieuw.",
  "Translations are automatic and may contain errors.": "De vertalingen zijn automatisch en kunnen fouten bevatten.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Wil je dat er een pictogram aan de mod wordt toegevoegd? Laat het ons weten in de Planetary Annihilation-Discord, kanaal #making-mods.",
  "Icon quality (Outline / Bevel)": "Pictogramkwaliteit (Omlijning / Afschuining)",
  "Standard (52 px)": "Standaard (52 px)",
  "High (104 px)": "Hoog (104 px)",
  "Very high (208 px)": "Zeer hoog (208 px)"
 },
 "no": {
  "ICONS": "IKONER",
  "UNIT ICONS": "ENHETSIKONER",
  "Icon style": "Ikonstil",
  "Original (game icons)": "Original (spillets ikoner)",
  "Outline": "Omriss",
  "Bevel": "Avfasing",
  "Strategic icon size": "Størrelse på strategiske ikoner",
  "Strategic icon opacity": "Gjennomsiktighet for strategiske ikoner",
  "Unit portrait opacity (selection / build bar)": "Gjennomsiktighet for enhetens portrett (valg / byggelinje)",
  "STYLE BY DOMAIN": "STIL ETTER DOMENE",
  "SIZE AND OPACITY BY CATEGORY": "STØRRELSE OG GJENNOMSIKTIGHET ETTER KATEGORI",
  "RADAR BLIPS": "RADARPRIKKER",
  "PRESETS AND RESET": "FORHÅNDSINNSTILLINGER OG NULLSTILLING",
  "Same as general": "Samme som generelt",
  "Style: land units": "Stil: landenheter",
  "Style: naval units": "Stil: sjøenheter",
  "Style: air units": "Stil: luftenheter",
  "Style: orbital units": "Stil: orbitale enheter",
  "Style: structures": "Stil: bygninger",
  "Size: units": "Størrelse: enheter",
  "Size: structures": "Størrelse: bygninger",
  "Size: orbital units": "Størrelse: orbitale enheter",
  "Opacity: units": "Gjennomsiktighet: enheter",
  "Opacity: structures": "Gjennomsiktighet: bygninger",
  "Opacity: orbital units": "Gjennomsiktighet: orbitale enheter",
  "Blip opacity": "Gjennomsiktighet for prikker",
  "Blip color": "Farge på prikker",
  "Preset": "Forhåndsinnstilling",
  "Team color": "Lagfarge",
  "Red": "Rød",
  "Yellow": "Gul",
  "Green": "Grønn",
  "Cyan": "Cyan",
  "Blue": "Blå",
  "Magenta": "Magenta",
  "White": "Hvit",
  "Custom": "Egendefinert",
  "Default": "Standard",
  "Discreet": "Diskret",
  "High contrast": "Høy kontrast",
  "Reset to defaults": "Tilbakestill til standard",
  "SELECTION AND HOVER RINGS": "VALG- OG PEKERRINGER",
  "Selection ring style": "Stil på valgringen",
  "Rainbow (dom314)": "Regnbue (dom314)",
  "Hover ring color": "Farge på pekerringen",
  "Ring changes reload the game view.": "Endringer i ringene laster spillvisningen på nytt.",
  "Translations are automatic and may contain errors.": "Oversettelsene er automatiske og kan inneholde feil.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Vil du ha et ikon lagt til i modden? Si fra på Planetary Annihilations Discord, kanalen #making-mods.",
  "Icon quality (Outline / Bevel)": "Ikonkvalitet (Omriss / Skråkant)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Høy (104 px)",
  "Very high (208 px)": "Svært høy (208 px)"
 },
 "ro": {
  "ICONS": "PICTOGRAME",
  "UNIT ICONS": "PICTOGRAMELE UNITĂȚILOR",
  "Icon style": "Stilul pictogramelor",
  "Original (game icons)": "Original (pictogramele jocului)",
  "Outline": "Contur",
  "Bevel": "Teșit",
  "Strategic icon size": "Dimensiunea pictogramelor strategice",
  "Strategic icon opacity": "Opacitatea pictogramelor strategice",
  "Unit portrait opacity (selection / build bar)": "Opacitatea portretului unității (selecție / bara de construcție)",
  "STYLE BY DOMAIN": "STIL PE DOMENII",
  "SIZE AND OPACITY BY CATEGORY": "DIMENSIUNE ȘI OPACITATE PE CATEGORII",
  "RADAR BLIPS": "SEMNALE RADAR",
  "PRESETS AND RESET": "PRESETĂRI ȘI RESETARE",
  "Same as general": "La fel ca setarea generală",
  "Style: land units": "Stil: unități terestre",
  "Style: naval units": "Stil: unități navale",
  "Style: air units": "Stil: unități aeriene",
  "Style: orbital units": "Stil: unități orbitale",
  "Style: structures": "Stil: structuri",
  "Size: units": "Dimensiune: unități",
  "Size: structures": "Dimensiune: structuri",
  "Size: orbital units": "Dimensiune: unități orbitale",
  "Opacity: units": "Opacitate: unități",
  "Opacity: structures": "Opacitate: structuri",
  "Opacity: orbital units": "Opacitate: unități orbitale",
  "Blip opacity": "Opacitatea semnalelor",
  "Blip color": "Culoarea semnalelor",
  "Preset": "Presetare",
  "Team color": "Culoarea echipei",
  "Red": "Roșu",
  "Yellow": "Galben",
  "Green": "Verde",
  "Cyan": "Cian",
  "Blue": "Albastru",
  "Magenta": "Magenta",
  "White": "Alb",
  "Custom": "Personalizat",
  "Default": "Implicit",
  "Discreet": "Discret",
  "High contrast": "Contrast ridicat",
  "Reset to defaults": "Resetează la implicit",
  "SELECTION AND HOVER RINGS": "INELE DE SELECTARE ȘI INDICARE",
  "Selection ring style": "Stilul inelului de selectare",
  "Rainbow (dom314)": "Curcubeu (dom314)",
  "Hover ring color": "Culoarea inelului de indicare",
  "Ring changes reload the game view.": "Modificările inelelor reîncarcă vizualizarea jocului.",
  "Translations are automatic and may contain errors.": "Traducerile sunt automate și pot conține erori.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Vrei să adăugăm o pictogramă în mod? Spune-ne pe Discord-ul Planetary Annihilation, canalul #making-mods.",
  "Icon quality (Outline / Bevel)": "Calitatea pictogramelor (Contur / Teșit)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Înaltă (104 px)",
  "Very high (208 px)": "Foarte înaltă (208 px)"
 },
 "sv": {
  "ICONS": "IKONER",
  "UNIT ICONS": "ENHETSIKONER",
  "Icon style": "Ikonstil",
  "Original (game icons)": "Original (spelets ikoner)",
  "Outline": "Kontur",
  "Bevel": "Fasad kant",
  "Strategic icon size": "Storlek på strategiska ikoner",
  "Strategic icon opacity": "Opacitet för strategiska ikoner",
  "Unit portrait opacity (selection / build bar)": "Opacitet för enhetens porträtt (val / byggfält)",
  "STYLE BY DOMAIN": "STIL PER DOMÄN",
  "SIZE AND OPACITY BY CATEGORY": "STORLEK OCH OPACITET PER KATEGORI",
  "RADAR BLIPS": "RADARPRICKAR",
  "PRESETS AND RESET": "FÖRINSTÄLLNINGAR OCH ÅTERSTÄLLNING",
  "Same as general": "Samma som allmänt",
  "Style: land units": "Stil: markenheter",
  "Style: naval units": "Stil: sjöenheter",
  "Style: air units": "Stil: luftenheter",
  "Style: orbital units": "Stil: orbitala enheter",
  "Style: structures": "Stil: byggnader",
  "Size: units": "Storlek: enheter",
  "Size: structures": "Storlek: byggnader",
  "Size: orbital units": "Storlek: orbitala enheter",
  "Opacity: units": "Opacitet: enheter",
  "Opacity: structures": "Opacitet: byggnader",
  "Opacity: orbital units": "Opacitet: orbitala enheter",
  "Blip opacity": "Opacitet för prickar",
  "Blip color": "Färg på prickar",
  "Preset": "Förinställning",
  "Team color": "Lagfärg",
  "Red": "Röd",
  "Yellow": "Gul",
  "Green": "Grön",
  "Cyan": "Cyan",
  "Blue": "Blå",
  "Magenta": "Magenta",
  "White": "Vit",
  "Custom": "Anpassad",
  "Default": "Standard",
  "Discreet": "Diskret",
  "High contrast": "Hög kontrast",
  "Reset to defaults": "Återställ till standard",
  "SELECTION AND HOVER RINGS": "MARKERINGS- OCH PEKARRINGAR",
  "Selection ring style": "Markeringsringens stil",
  "Rainbow (dom314)": "Regnbåge (dom314)",
  "Hover ring color": "Pekarringens färg",
  "Ring changes reload the game view.": "Ändringar av ringar laddar om spelvyn.",
  "Translations are automatic and may contain errors.": "Översättningarna är automatiska och kan innehålla fel.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Vill du att en ikon läggs till i modden? Hör av dig på Planetary Annihilations Discord, kanalen #making-mods.",
  "Icon quality (Outline / Bevel)": "Ikonkvalitet (Kontur / Fasning)",
  "Standard (52 px)": "Standard (52 px)",
  "High (104 px)": "Hög (104 px)",
  "Very high (208 px)": "Mycket hög (208 px)"
 },
 "tr": {
  "ICONS": "SİMGELER",
  "UNIT ICONS": "BİRİM SİMGELERİ",
  "Icon style": "Simge stili",
  "Original (game icons)": "Orijinal (oyun simgeleri)",
  "Outline": "Kontur",
  "Bevel": "Eğimli",
  "Strategic icon size": "Stratejik simge boyutu",
  "Strategic icon opacity": "Stratejik simge opaklığı",
  "Unit portrait opacity (selection / build bar)": "Birim portresi opaklığı (seçim / inşa çubuğu)",
  "STYLE BY DOMAIN": "ALANA GÖRE STİL",
  "SIZE AND OPACITY BY CATEGORY": "KATEGORİYE GÖRE BOYUT VE OPAKLIK",
  "RADAR BLIPS": "RADAR İŞARETLERİ",
  "PRESETS AND RESET": "ÖN AYARLAR VE SIFIRLAMA",
  "Same as general": "Genel ile aynı",
  "Style: land units": "Stil: kara birimleri",
  "Style: naval units": "Stil: deniz birimleri",
  "Style: air units": "Stil: hava birimleri",
  "Style: orbital units": "Stil: yörünge birimleri",
  "Style: structures": "Stil: yapılar",
  "Size: units": "Boyut: birimler",
  "Size: structures": "Boyut: yapılar",
  "Size: orbital units": "Boyut: yörünge birimleri",
  "Opacity: units": "Opaklık: birimler",
  "Opacity: structures": "Opaklık: yapılar",
  "Opacity: orbital units": "Opaklık: yörünge birimleri",
  "Blip opacity": "İşaret opaklığı",
  "Blip color": "İşaret rengi",
  "Preset": "Ön ayar",
  "Team color": "Takım rengi",
  "Red": "Kırmızı",
  "Yellow": "Sarı",
  "Green": "Yeşil",
  "Cyan": "Camgöbeği",
  "Blue": "Mavi",
  "Magenta": "Eflatun",
  "White": "Beyaz",
  "Custom": "Özel",
  "Default": "Varsayılan",
  "Discreet": "Gösterişsiz",
  "High contrast": "Yüksek karşıtlık",
  "Reset to defaults": "Varsayılana sıfırla",
  "SELECTION AND HOVER RINGS": "SEÇİM VE İMLEÇ HALKALARI",
  "Selection ring style": "Seçim halkası stili",
  "Rainbow (dom314)": "Gökkuşağı (dom314)",
  "Hover ring color": "İmleç halkası rengi",
  "Ring changes reload the game view.": "Halka değişiklikleri oyun görünümünü yeniden yükler.",
  "Translations are automatic and may contain errors.": "Çeviriler otomatiktir ve hata içerebilir.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "Moda bir simge eklenmesini ister misin? Planetary Annihilation Discord'unda #making-mods kanalından bize bildir.",
  "Icon quality (Outline / Bevel)": "Simge kalitesi (Taslak / Pah)",
  "Standard (52 px)": "Standart (52 px)",
  "High (104 px)": "Yüksek (104 px)",
  "Very high (208 px)": "Çok yüksek (208 px)"
 },
 "ja": {
  "ICONS": "アイコン",
  "UNIT ICONS": "ユニットアイコン",
  "Icon style": "アイコンのスタイル",
  "Original (game icons)": "オリジナル（ゲームのアイコン）",
  "Outline": "アウトライン",
  "Bevel": "ベベル",
  "Strategic icon size": "戦略アイコンのサイズ",
  "Strategic icon opacity": "戦略アイコンの不透明度",
  "Unit portrait opacity (selection / build bar)": "ユニット肖像の不透明度（選択 / 建設バー）",
  "STYLE BY DOMAIN": "領域別スタイル",
  "SIZE AND OPACITY BY CATEGORY": "カテゴリ別のサイズと不透明度",
  "RADAR BLIPS": "レーダー反応",
  "PRESETS AND RESET": "プリセットとリセット",
  "Same as general": "全体設定と同じ",
  "Style: land units": "スタイル: 地上ユニット",
  "Style: naval units": "スタイル: 海上ユニット",
  "Style: air units": "スタイル: 航空ユニット",
  "Style: orbital units": "スタイル: 軌道ユニット",
  "Style: structures": "スタイル: 建造物",
  "Size: units": "サイズ: ユニット",
  "Size: structures": "サイズ: 建造物",
  "Size: orbital units": "サイズ: 軌道ユニット",
  "Opacity: units": "不透明度: ユニット",
  "Opacity: structures": "不透明度: 建造物",
  "Opacity: orbital units": "不透明度: 軌道ユニット",
  "Blip opacity": "反応の不透明度",
  "Blip color": "反応の色",
  "Preset": "プリセット",
  "Team color": "チームカラー",
  "Red": "赤",
  "Yellow": "黄",
  "Green": "緑",
  "Cyan": "シアン",
  "Blue": "青",
  "Magenta": "マゼンタ",
  "White": "白",
  "Custom": "カスタム",
  "Default": "デフォルト",
  "Discreet": "控えめ",
  "High contrast": "高コントラスト",
  "Reset to defaults": "初期値に戻す",
  "SELECTION AND HOVER RINGS": "選択・ホバーリング",
  "Selection ring style": "選択リングのスタイル",
  "Rainbow (dom314)": "虹色（dom314）",
  "Hover ring color": "ホバーリングの色",
  "Ring changes reload the game view.": "リングの変更はゲームの表示を再読み込みします。",
  "Translations are automatic and may contain errors.": "翻訳は自動生成のため、誤りが含まれている場合があります。",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "MODにアイコンを追加してほしいですか？Planetary AnnihilationのDiscord、#making-modsチャンネルでお知らせください。",
  "Icon quality (Outline / Bevel)": "アイコンの品質（アウトライン／ベベル）",
  "Standard (52 px)": "標準 (52 px)",
  "High (104 px)": "高 (104 px)",
  "Very high (208 px)": "最高 (208 px)"
 },
 "ko": {
  "ICONS": "아이콘",
  "UNIT ICONS": "유닛 아이콘",
  "Icon style": "아이콘 스타일",
  "Original (game icons)": "원본(게임 아이콘)",
  "Outline": "윤곽선",
  "Bevel": "베벨",
  "Strategic icon size": "전략 아이콘 크기",
  "Strategic icon opacity": "전략 아이콘 불투명도",
  "Unit portrait opacity (selection / build bar)": "유닛 초상화 불투명도(선택 / 건설 바)",
  "STYLE BY DOMAIN": "영역별 스타일",
  "SIZE AND OPACITY BY CATEGORY": "범주별 크기 및 불투명도",
  "RADAR BLIPS": "레이더 신호",
  "PRESETS AND RESET": "프리셋 및 초기화",
  "Same as general": "전체 설정과 동일",
  "Style: land units": "스타일: 지상 유닛",
  "Style: naval units": "스타일: 해상 유닛",
  "Style: air units": "스타일: 공중 유닛",
  "Style: orbital units": "스타일: 궤도 유닛",
  "Style: structures": "스타일: 건물",
  "Size: units": "크기: 유닛",
  "Size: structures": "크기: 건물",
  "Size: orbital units": "크기: 궤도 유닛",
  "Opacity: units": "불투명도: 유닛",
  "Opacity: structures": "불투명도: 건물",
  "Opacity: orbital units": "불투명도: 궤도 유닛",
  "Blip opacity": "신호 불투명도",
  "Blip color": "신호 색상",
  "Preset": "프리셋",
  "Team color": "팀 색상",
  "Red": "빨강",
  "Yellow": "노랑",
  "Green": "초록",
  "Cyan": "청록",
  "Blue": "파랑",
  "Magenta": "자홍",
  "White": "흰색",
  "Custom": "사용자 지정",
  "Default": "기본값",
  "Discreet": "은은하게",
  "High contrast": "고대비",
  "Reset to defaults": "기본값으로 초기화",
  "SELECTION AND HOVER RINGS": "선택 및 호버 링",
  "Selection ring style": "선택 링 스타일",
  "Rainbow (dom314)": "무지개 (dom314)",
  "Hover ring color": "호버 링 색상",
  "Ring changes reload the game view.": "링 변경 사항은 게임 화면을 다시 불러옵니다.",
  "Translations are automatic and may contain errors.": "번역은 자동으로 생성되었으며 오류가 있을 수 있습니다.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "모드에 아이콘을 추가하고 싶으신가요? Planetary Annihilation Discord의 #making-mods 채널에서 알려 주세요.",
  "Icon quality (Outline / Bevel)": "아이콘 품질 (윤곽선 / 베벨)",
  "Standard (52 px)": "표준 (52 px)",
  "High (104 px)": "높음 (104 px)",
  "Very high (208 px)": "매우 높음 (208 px)"
 },
 "ar": {
  "ICONS": "الأيقونات",
  "UNIT ICONS": "أيقونات الوحدات",
  "Icon style": "نمط الأيقونات",
  "Original (game icons)": "الأصلي (أيقونات اللعبة)",
  "Outline": "مخطط",
  "Bevel": "مشطوف",
  "Strategic icon size": "حجم الأيقونات الاستراتيجية",
  "Strategic icon opacity": "عتامة الأيقونات الاستراتيجية",
  "Unit portrait opacity (selection / build bar)": "عتامة صورة الوحدة (التحديد / شريط البناء)",
  "STYLE BY DOMAIN": "النمط حسب المجال",
  "SIZE AND OPACITY BY CATEGORY": "الحجم والعتامة حسب الفئة",
  "RADAR BLIPS": "إشارات الرادار",
  "PRESETS AND RESET": "الإعدادات المسبقة وإعادة الضبط",
  "Same as general": "مثل الإعداد العام",
  "Style: land units": "النمط: الوحدات البرية",
  "Style: naval units": "النمط: الوحدات البحرية",
  "Style: air units": "النمط: الوحدات الجوية",
  "Style: orbital units": "النمط: الوحدات المدارية",
  "Style: structures": "النمط: المنشآت",
  "Size: units": "الحجم: الوحدات",
  "Size: structures": "الحجم: المنشآت",
  "Size: orbital units": "الحجم: الوحدات المدارية",
  "Opacity: units": "العتامة: الوحدات",
  "Opacity: structures": "العتامة: المنشآت",
  "Opacity: orbital units": "العتامة: الوحدات المدارية",
  "Blip opacity": "عتامة الإشارات",
  "Blip color": "لون الإشارات",
  "Preset": "إعداد مسبق",
  "Team color": "لون الفريق",
  "Red": "أحمر",
  "Yellow": "أصفر",
  "Green": "أخضر",
  "Cyan": "سماوي",
  "Blue": "أزرق",
  "Magenta": "أرجواني",
  "White": "أبيض",
  "Custom": "مخصص",
  "Default": "افتراضي",
  "Discreet": "خفيف",
  "High contrast": "تباين عالٍ",
  "Reset to defaults": "إعادة الضبط إلى الافتراضي",
  "SELECTION AND HOVER RINGS": "حلقات التحديد والتمرير",
  "Selection ring style": "نمط حلقة التحديد",
  "Rainbow (dom314)": "قوس قزح (dom314)",
  "Hover ring color": "لون حلقة التمرير",
  "Ring changes reload the game view.": "تؤدي تغييرات الحلقات إلى إعادة تحميل عرض اللعبة.",
  "Translations are automatic and may contain errors.": "الترجمات آلية وقد تحتوي على أخطاء.",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "هل تريد إضافة أيقونة إلى المود؟ أخبرنا في ديسكورد Planetary Annihilation، قناة #making-mods.",
  "Icon quality (Outline / Bevel)": "جودة الأيقونات (مخطط / مشطوف)",
  "Standard (52 px)": "قياسية (52 px)",
  "High (104 px)": "عالية (104 px)",
  "Very high (208 px)": "عالية جدًا (208 px)"
 },
 "zh-CN": {
  "ICONS": "图标",
  "UNIT ICONS": "单位图标",
  "Icon style": "图标样式",
  "Original (game icons)": "原版（游戏图标）",
  "Outline": "轮廓",
  "Bevel": "斜面",
  "Strategic icon size": "战略图标大小",
  "Strategic icon opacity": "战略图标不透明度",
  "Unit portrait opacity (selection / build bar)": "单位头像不透明度（选择 / 建造栏）",
  "STYLE BY DOMAIN": "按领域设置样式",
  "SIZE AND OPACITY BY CATEGORY": "按类别设置大小和不透明度",
  "RADAR BLIPS": "雷达信号",
  "PRESETS AND RESET": "预设与重置",
  "Same as general": "与总体设置相同",
  "Style: land units": "样式: 地面单位",
  "Style: naval units": "样式: 海上单位",
  "Style: air units": "样式: 空中单位",
  "Style: orbital units": "样式: 轨道单位",
  "Style: structures": "样式: 建筑",
  "Size: units": "大小: 单位",
  "Size: structures": "大小: 建筑",
  "Size: orbital units": "大小: 轨道单位",
  "Opacity: units": "不透明度: 单位",
  "Opacity: structures": "不透明度: 建筑",
  "Opacity: orbital units": "不透明度: 轨道单位",
  "Blip opacity": "信号不透明度",
  "Blip color": "信号颜色",
  "Preset": "预设",
  "Team color": "队伍颜色",
  "Red": "红色",
  "Yellow": "黄色",
  "Green": "绿色",
  "Cyan": "青色",
  "Blue": "蓝色",
  "Magenta": "品红",
  "White": "白色",
  "Custom": "自定义",
  "Default": "默认",
  "Discreet": "低调",
  "High contrast": "高对比度",
  "Reset to defaults": "恢复默认值",
  "SELECTION AND HOVER RINGS": "选择与悬停圆环",
  "Selection ring style": "选择圆环样式",
  "Rainbow (dom314)": "彩虹（dom314）",
  "Hover ring color": "悬停圆环颜色",
  "Ring changes reload the game view.": "圆环更改会重新加载游戏画面。",
  "Translations are automatic and may contain errors.": "翻译为自动生成，可能存在错误。",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "想让模组新增一个图标吗？请到 Planetary Annihilation 的 Discord、#making-mods 频道告诉我们。",
  "Icon quality (Outline / Bevel)": "图标质量（轮廓 / 斜面）",
  "Standard (52 px)": "标准 (52 px)",
  "High (104 px)": "高 (104 px)",
  "Very high (208 px)": "超高 (208 px)"
 },
 "zh-TW": {
  "ICONS": "圖示",
  "UNIT ICONS": "單位圖示",
  "Icon style": "圖示樣式",
  "Original (game icons)": "原版（遊戲圖示）",
  "Outline": "輪廓",
  "Bevel": "斜角",
  "Strategic icon size": "戰略圖示大小",
  "Strategic icon opacity": "戰略圖示不透明度",
  "Unit portrait opacity (selection / build bar)": "單位肖像不透明度（選擇 / 建造列）",
  "STYLE BY DOMAIN": "依領域設定樣式",
  "SIZE AND OPACITY BY CATEGORY": "依類別設定大小與不透明度",
  "RADAR BLIPS": "雷達訊號",
  "PRESETS AND RESET": "預設與重設",
  "Same as general": "與整體設定相同",
  "Style: land units": "樣式: 地面單位",
  "Style: naval units": "樣式: 海上單位",
  "Style: air units": "樣式: 空中單位",
  "Style: orbital units": "樣式: 軌道單位",
  "Style: structures": "樣式: 建築",
  "Size: units": "大小: 單位",
  "Size: structures": "大小: 建築",
  "Size: orbital units": "大小: 軌道單位",
  "Opacity: units": "不透明度: 單位",
  "Opacity: structures": "不透明度: 建築",
  "Opacity: orbital units": "不透明度: 軌道單位",
  "Blip opacity": "訊號不透明度",
  "Blip color": "訊號顏色",
  "Preset": "預設",
  "Team color": "隊伍顏色",
  "Red": "紅色",
  "Yellow": "黃色",
  "Green": "綠色",
  "Cyan": "青色",
  "Blue": "藍色",
  "Magenta": "洋紅",
  "White": "白色",
  "Custom": "自訂",
  "Default": "預設值",
  "Discreet": "低調",
  "High contrast": "高對比",
  "Reset to defaults": "還原預設值",
  "SELECTION AND HOVER RINGS": "選取與懸停圓環",
  "Selection ring style": "選取圓環樣式",
  "Rainbow (dom314)": "彩虹（dom314）",
  "Hover ring color": "懸停圓環顏色",
  "Ring changes reload the game view.": "圓環變更會重新載入遊戲畫面。",
  "Translations are automatic and may contain errors.": "翻譯為自動產生，可能有錯誤。",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "想讓模組新增一個圖示嗎？請到 Planetary Annihilation 的 Discord、#making-mods 頻道告訴我們。",
  "Icon quality (Outline / Bevel)": "圖示品質（輪廓 / 斜角）",
  "Standard (52 px)": "標準 (52 px)",
  "High (104 px)": "高 (104 px)",
  "Very high (208 px)": "超高 (208 px)"
 },
 "zh-HK": {
  "ICONS": "圖示",
  "UNIT ICONS": "單位圖示",
  "Icon style": "圖示樣式",
  "Original (game icons)": "原版（遊戲圖示）",
  "Outline": "輪廓",
  "Bevel": "斜角",
  "Strategic icon size": "戰略圖示大小",
  "Strategic icon opacity": "戰略圖示不透明度",
  "Unit portrait opacity (selection / build bar)": "單位肖像不透明度（選擇 / 建造列）",
  "STYLE BY DOMAIN": "依領域設定樣式",
  "SIZE AND OPACITY BY CATEGORY": "依類別設定大小與不透明度",
  "RADAR BLIPS": "雷達訊號",
  "PRESETS AND RESET": "預設與重設",
  "Same as general": "與整體設定相同",
  "Style: land units": "樣式: 地面單位",
  "Style: naval units": "樣式: 海上單位",
  "Style: air units": "樣式: 空中單位",
  "Style: orbital units": "樣式: 軌道單位",
  "Style: structures": "樣式: 建築",
  "Size: units": "大小: 單位",
  "Size: structures": "大小: 建築",
  "Size: orbital units": "大小: 軌道單位",
  "Opacity: units": "不透明度: 單位",
  "Opacity: structures": "不透明度: 建築",
  "Opacity: orbital units": "不透明度: 軌道單位",
  "Blip opacity": "訊號不透明度",
  "Blip color": "訊號顏色",
  "Preset": "預設",
  "Team color": "隊伍顏色",
  "Red": "紅色",
  "Yellow": "黃色",
  "Green": "綠色",
  "Cyan": "青色",
  "Blue": "藍色",
  "Magenta": "洋紅",
  "White": "白色",
  "Custom": "自訂",
  "Default": "預設值",
  "Discreet": "低調",
  "High contrast": "高對比",
  "Reset to defaults": "還原預設值",
  "SELECTION AND HOVER RINGS": "選取與懸停圓環",
  "Selection ring style": "選取圓環樣式",
  "Rainbow (dom314)": "彩虹（dom314）",
  "Hover ring color": "懸停圓環顏色",
  "Ring changes reload the game view.": "圓環變更會重新載入遊戲畫面。",
  "Translations are automatic and may contain errors.": "翻譯為自動產生，可能有錯誤。",
  "Want an icon added to the mod? Let us know in the Planetary Annihilation Discord, channel #making-mods.": "想讓模組新增一個圖示嗎？請到 Planetary Annihilation 的 Discord、#making-mods 頻道告訴我們。",
  "Icon quality (Outline / Bevel)": "圖示品質（輪廓 / 斜角）",
  "Standard (52 px)": "標準 (52 px)",
  "High (104 px)": "高 (104 px)",
  "Very high (208 px)": "超高 (208 px)"
 }
};
    IconosOpc.TRAD = TRAD;
    IconosOpc.registrarIdiomas = function () {
        try {
            if (IconosOpc._idiomaListo || !window.i18n || !i18n.addResourceBundle || !i18n.lng) { return; }
            var lng = i18n.lng(), t = TRAD[lng] || TRAD[String(lng).split('-')[0]];
            if (t) { i18n.addResourceBundle(lng, 'translation', t); }
            IconosOpc._idiomaListo = true;
        } catch (e) {}
    };
})();
